### ISSUE TITLE
how does fritter dat have write access to my profile dat?

### ISSUE THREAD

**Issue by forresto** [beakerbrowser/libfritter#1]
This is probably a basic dat/beaker feature, but I don't see how that write permission is granted / known by the app. In Rotonde, it is writing to its own archive.

( Also asked on Fritter 😉 ... I like how threads are linkable: dat://9900f9aad4d6e79e0beb1c46333852b99829e4dfcdfa9b690eeeab3c367c1b9a/thread/dat://60ab33befcf17cd64ca35a5afcffbc65e8763ff0643692df554b90fad7de8b45/posts/0jc9ettgs.json )

**Comment by pfrazee** [comment]
This works because any Dat created by a site is automatically given write access. Since fritter created your profile dat, it gets write access.

You can see the perms by clicking on the site info:
![screen shot 2018-01-10 at 12 50 36 pm](https://user-images.githubusercontent.com/1270099/34789726-ff8c0f08-f604-11e7-9679-6d04c892060f.png)

**Comment by bertoni** [comment]
To enjoy this opened issue, it's possible I access my profile by another device? Or the Fritter is a singlewriter app?

**Comment by pfrazee** [comment]
@bertoni not yet. We're still working on multiwriter support for Dat

**Comment by arni077** [comment]
@pfrazee how to give others permission to write on my files?

**Comment by arni077** [comment]
@pfrazee help please, i don't understand how Dat can be created by a site. how the basic idea works? 
i tried to implement the code, but when a user uploads my site from his computer and clicks the button to create new archive, he gets the error - "not the owner"
